### ISSUE TITLE
As a user, I can read an article

### ISSUE THREAD

**Issue by jeffgore00** [DJA1802/context#7]
- [x] #13 Create `Article` component to represent a single article for reading
- [x] #37 Create route in `api/articles` to make Mercury API request
- [x] #38 Make clean-up script for data returned from Mercury API
