### ISSUE TITLE
As a user, I can filter, sort, and search through Articles that I've saved

### ISSUE THREAD

**Issue by dleistman** [DJA1802/context#73]
- [ ] #22 Allow users to sort ArticleListItems in view by multiple criteria
- [ ] #23 Allow users to filter ArticleListItems in view by multiple criteria
- [ ] #63 Users can search for an article in their saved articles
