### ISSUE TITLE
As a user, I can navigate around the site easily and freely

### ISSUE THREAD

**Issue by jeffgore00** [DJA1802/context#8]
- [x] #47 Create the NavBar component 
- [x] #14 Style the NavBar component
- [x] #15 In an Article view, the NavBar component should be minimized to a simple hamburger icon
- [x] #16 Set up routes for single Article view, and ArticleList
